### ISSUE TITLE
manager放在install里面了... 

### ISSUE THREAD

**Issue by lazybootsafe** [tongchengbin/ocean_ctf#1]
挪出来~

**Comment by lazybootsafe** [comment]
还有一些小bug，比如后台添加题目处，无法点击 取消 就直接卡死了，我看了看ctf_view.py 貌似没看到有啥问题。而且和您给出的截图好像功能不一致...

**Comment by tongchengbin** [comment]
> 还有一些小bug，比如后台添加题目处，无法点击 取消 就直接卡死了，我看了看ctf_view.py 貌似没看到有啥问题。而且和您给出的截图好像功能不一致...

应该是没有给取消添加事件，如果对这个项目感兴趣可以协同开发，一个人的时间有限。

**Comment by tongchengbin** [comment]
> 挪出来~

放在install 里面的主要原因是在manager 是一个打包文件 并不是使用的flask的模板渲染 也不能做修改；在服务器上部署直接用nginx当作静态文件就可以了，为了方便套用了一个flask的静态文件路径可以直接访问，但是实际部署不会用到flask解析。

**Comment by lazybootsafe** [comment]
> > 挪出来~
> 
> 放在install 里面的主要原因是在manager 是一个打包文件 并不是使用的flask的模板渲染 也不能做修改；在服务器上部署直接用nginx当作静态文件就可以了，为了方便套用了一个flask的静态文件路径可以直接访问，但是实际部署不会用到flask解析。

哦哦 我直接一个一个文件看的... 我基于CTFD开发的，您的这套感觉写的更好，更合适我的审美。我这边也怕时间不是很充足，都集中在题库这块了。。
