### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by limu520** [tongchengbin/ocean_ctf#11]
###问题一：
git最新的仓库进行build docker镜像，build过程失败。
检查后发现requirment.txt中的click库出现依赖冲突的问题：
`解决方案：更改requirment.txt文件的click的具体版本，删除两个click的行，添加一个click`
解决build的问题。

###问题二：

容器正常运行，访问出现报错Internal Server Error，
检查log文件，发现提示“ no python application found, check your startup logs for errors”

经过debug过程发现是uwsgi.ini文件的wsgi-file路径出现错误：

更改为/opt/ocean_ctf/main.py，页面即可正常访问。

**Comment by vFREE-1** [comment]
你好，默认的账号密码是多少哇

**Comment by limu520** [comment]
> 你好，默认的账号密码是多少哇

访客账号 test/test
默认超级管理员账号 superuser/admin

**Comment by vFREE-1** [comment]
好的，谢谢，还想问一个问题，哪个进阶文档是不是也要弄，要不然是不是添加不了容器主机

**Comment by tongchengbin** [comment]
进阶按照本地配置即可

**Comment by limu520** [comment]
已收到
