### ISSUE TITLE
登录界面刷新会404

### ISSUE THREAD

**Issue by wanswu** [tongchengbin/ocean_ctf#17]
{
  "code": 404, 
  "msg": "Not Found"
}

**Comment by tongchengbin** [comment]
url 发一下

**Comment by wanswu** [comment]
http://94.74.111.52:8080/login

**Comment by wanswu** [comment]
> url 发一下

https://94.74.111.52:8080/login

**Comment by wanswu** [comment]
> url 发一下

就是那个主页然后点击登录，然后在登录界面刷新一下就会404

**Comment by wanswu** [comment]
> url 发一下

答题界面开启一个容器之后会一直弹提交flag页面

**Comment by Thatsman** [comment]
因为vue-router的mode使用了history模式，默认应该是hash模式
在nginx的配置文件的location位置加上 try_files $uri $uri/ /index.html;重新加载就好了
![image](https://user-images.githubusercontent.com/96039221/162161340-3307d6f1-9a5c-4e00-926d-699bc0a26fb5.png)

**Comment by tongchengbin** [comment]
> 这是因为vue-router的mode使用了history模式，默认应该是hash模式 只需要在nginx配置文件的location加上 try_files $uri $uri/ /index.html; 再重新加载就好了 ![image](https://user-images.githubusercontent.com/96039221/162161340-3307d6f1-9a5c-4e00-926d-699bc0a26fb5.png)



> 这是因为vue-router的mode使用了history模式，默认应该是hash模式 只需要在nginx配置文件的location加上 try_files $uri $uri/ /index.html; 再重新加载就好了 ![image](https://user-images.githubusercontent.com/96039221/162161340-3307d6f1-9a5c-4e00-926d-699bc0a26fb5.png)

目前部署没有经过nginx所以会出现这个问题、下个版本会修复的。

**Comment by wanswu** [comment]
> > 这是因为vue-router的mode使用了history模式，默认应该是hash模式 只需要在nginx配置文件的location加上 try_files $uri $uri/ /index.html; 再重新加载就好了 ![image](https://user-images.githubusercontent.com/96039221/162161340-3307d6f1-9a5c-4e00-926d-699bc0a26fb5.png)
> 
> > 这是因为vue-router的mode使用了history模式，默认应该是hash模式 只需要在nginx配置文件的location加上 try_files $uri $uri/ /index.html; 再重新加载就好了 ![image](https://user-images.githubusercontent.com/96039221/162161340-3307d6f1-9a5c-4e00-926d-699bc0a26fb5.png)
> 
> 目前部署没有经过nginx所以会出现这个问题、下个版本会修复的。

您好，我基于您的前端，用django也写了一个，可以开源吗

**Comment by wanswu** [comment]
您好，我基于您的前端，用django也写了一个，可以开源吗

> > 这是因为vue-router的mode使用了history模式，默认应该是hash模式 只需要在nginx配置文件的location加上 try_files $uri $uri/ /index.html; 再重新加载就好了 ![image](https://user-images.githubusercontent.com/96039221/162161340-3307d6f1-9a5c-4e00-926d-699bc0a26fb5.png)
> 
> > 这是因为vue-router的mode使用了history模式，默认应该是hash模式 只需要在nginx配置文件的location加上 try_files $uri $uri/ /index.html; 再重新加载就好了 ![image](https://user-images.githubusercontent.com/96039221/162161340-3307d6f1-9a5c-4e00-926d-699bc0a26fb5.png)
> 
> 目前部署没有经过nginx所以会出现这个问题、下个版本会修复的。

您好，我基于您的前端，用django也写了一个，之后是不是也可以开源。

**Comment by tongchengbin** [comment]
可以的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月10日(周日) 上午10:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tongchengbin/ocean_ctf] 登录界面刷新会404 (Issue #17)




 
您好，我基于您的前端，用django也写了一个，可以开源吗
   
这是因为vue-router的mode使用了history模式，默认应该是hash模式 只需要在nginx配置文件的location加上 try_files $uri $uri/ /index.html; 再重新加载就好了 
   
这是因为vue-router的mode使用了history模式，默认应该是hash模式 只需要在nginx配置文件的location加上 try_files $uri $uri/ /index.html; 再重新加载就好了 
  
目前部署没有经过nginx所以会出现这个问题、下个版本会修复的。
  
您好，我基于您的前端，用django也写了一个，之后是不是也可以开源。

**Comment by wanswu** [comment]
感谢大佬

**Comment by tongchengbin** [comment]
fixed
