### ISSUE TITLE
靶机格式问题

### ISSUE THREAD

**Issue by 96368a** [tongchengbin/ocean_ctf#18]
能不能对靶机的格式做一下更具体的说明，
使用 [强网杯2019upload](https://github.com/glzjin/qwb_2019_upload) 做测试，导入镜像成功构建，
但是题目在启动时会报‘服务器繁忙’，后台容器管理也看不到容器，但是用命令行查看时发现容器已被启动，另外flag也没有自动设置。
[平台测试网址](https://ctf.233c.cn)

（另外，你们考虑把文档写详细一点吗，我可以帮忙

**Comment by tongchengbin** [comment]
使用单文件dockerfile 构建好环境 然后将需要的文件打包成tar包 、在靶机中上传tar包即可 、启用start.sh 是更新flag的入口文件。如果有疑问可以添加主页联系方式
https://github.com/tongchengbin/ctfdb

**Comment by 96368a** [comment]
> 使用单文件环境好然后将需要的文件打包成tar包、在靶机中上传tar包即可、启用start.sh是更新标志的入口文件。如果有疑问可以添加主页联系 [方式github.com/tongchengbin/ctfdb](https://github.com/tongchengbin/ctfdb)

实测还是报一样的错误，报`服务器繁忙`，然后容器被开启了平台检测不到

**Comment by tongchengbin** [comment]
> 
更新一下代码、是因为设置flag会调用bash，但是该镜像中没有bash环境导致的错误；另外因为继承dockerfile的问题导致开放了多个端口所以平台检测的端口并不是web端口，不过这个属于镜像不规范问题。

**Comment by 96368a** [comment]
> > 
> 
> 更新一下代码、是因为设置flag会调用bash，但是该镜像中没有bash环境导致的错误；另外因为继承dockerfile的问题导致开放了多个端口所以平台检测的端口并不是web端口，不过这个属于镜像不规范问题。

bash环境问题我搞定了，多端口问题有没有什么解决方法啊
