### ISSUE TITLE
直接部署后无法添加镜像

### ISSUE THREAD

**Issue by paVVN** [tongchengbin/ocean_ctf#24]
![1649726228(1)](https://user-images.githubusercontent.com/40228542/162859295-0df14f45-cb34-4db0-90f2-be4b2c6db51c.jpg)

**Comment by tongchengbin** [comment]
请在动态镜像中添加镜像



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月12日(周二) 上午9:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [tongchengbin/ocean_ctf] 直接部署后无法添加镜像 (Issue #24)
