### ISSUE TITLE
使用docker-compose进行构建报错！

### ISSUE THREAD

**Issue by perlh** [tongchengbin/ocean_ctf#27]
PS C:\Users\HSM\Desktop\ocean_ctf-main\ocean_ctf-main> docker-compose up -d
[+] Running 26/27
 - nginx Pulled                                                                                                                                       46.2s
   - a2abf6c4d29d Pull complete                                                                                                                       22.7s
   - a9edb18cadd1 Pull complete                                                                                                                       27.6s
   - 589b7251471a Pull complete                                                                                                                       27.8s
   - 186b1aaa4aa6 Pull complete                                                                                                                       28.0s
   - b4df32aa5a72 Pull complete                                                                                                                       28.2s
   - a0bcbecc962e Pull complete                                                                                                                       28.3s
 - web Error                                                                                                                                           6.7s
 - db Pulled                                                                                                                                          59.0s
   - 72a69066d2fe Pull complete                                                                                                                       18.0s
   - 93619dbc5b36 Pull complete                                                                                                                       18.5s
   - 99da31dd6142 Pull complete                                                                                                                       19.8s
   - 626033c43d70 Pull complete                                                                                                                       21.3s
   - 37d5d7efb64e Pull complete                                                                                                                       21.6s
   - ac563158d721 Pull complete                                                                                                                       26.4s
   - d2ba16033dad Pull complete                                                                                                                       26.7s
   - 688ba7d5c01a Pull complete                                                                                                                       26.8s
   - 00e060b6d11d Pull complete                                                                                                                       41.1s
   - 1c04857f594f Pull complete                                                                                                                       41.1s
   - 4d7cfa90e6ea Pull complete                                                                                                                       41.2s
   - e0431212d27d Pull complete                                                                                                                       41.3s
 - redis Pulled                                                                                                                                       44.7s
   - c7a4e4382001 Pull complete                                                                                                                       22.9s
   - 4044b9ba67c9 Pull complete                                                                                                                       23.6s
   - c8388a79482f Pull complete                                                                                                                       26.3s
   - 413c8bb60be2 Pull complete                                                                                                                       26.6s
   - 1abfd3011519 Pull complete                                                                                                                       26.7s
[+] Building 122.5s (11/11) FINISHED
 => [internal] load build definition from ocean_web.Dockerfile                                                                                         0.1s
 => => transferring dockerfile: 383B                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/python:3.8.8                                                                                        1.3s
 => [1/6] FROM docker.io/library/python:3.8.8@sha256:e84c219fe873ab169551469f32b57facf7d7baded941ccf0cbcc54e4aefa6e80                                 66.9s
 => => resolve docker.io/library/python:3.8.8@sha256:e84c219fe873ab169551469f32b57facf7d7baded941ccf0cbcc54e4aefa6e80                                  0.0s
 => => sha256:004f1eed87df3f75f5e2a1a649fa7edd7f713d1300532fd0909bb39cd48437d7 50.43MB / 50.43MB                                                      28.8s
 => => sha256:48c2faf66abec3dce9f54d6722ff592fce6dd4fb58a0d0b72282936c6598a3b3 10.00MB / 10.00MB                                                       4.5s
 => => sha256:5d6f1e8117dbb1c6a57603cb4f321a861a08105a81bcc6b01b0ec2b78c8523a5 7.83MB / 7.83MB                                                         2.1s
 => => sha256:e84c219fe873ab169551469f32b57facf7d7baded941ccf0cbcc54e4aefa6e80 2.36kB / 2.36kB                                                         0.0s
 => => sha256:fe6fa34795ada8d9d6c1763205d06b5f402a8256946cacaaa7436f08568b574c 2.22kB / 2.22kB                                                         0.0s
 => => sha256:b182085023c0edc350b5b94df0219806d0a62eb70142fcbe20d8d34acc625c9f 8.38kB / 8.38kB                                                         0.0s
 => => sha256:234b70d0479d7f16d7ee8d04e4ffdacc57d7d14313faf59d332f18b2e9418743 51.84MB / 51.84MB                                                      16.5s
 => => sha256:6fa07a00e2f029c4b2c7f177a2b696f1b3510040cde4f5bb06ddbca98e7fbf76 192.35MB / 192.35MB                                                    48.1s
 => => sha256:04a31b4508b8e95fb3cb25486c4068185054895b12e0611e386a002ee9c0e07c 6.15MB / 6.15MB                                                        19.1s
 => => sha256:d71f59bc3dca0b4ed1abbeb5f8881d9038117b4afc5db3645ccde089855a0ff7 18.27MB / 18.27MB                                                      26.2s
 => => sha256:1417d35049f1a001c25031a8a86d6352a730aa7a4026a1bbac4c948c03c88a78 233B / 233B                                                            26.5s
 => => sha256:7deb1706395d9c9f7aceb648e2576c63f8faa97b520eb37f69559221aa8e9ac5 2.16MB / 2.16MB                                                        27.7s
 => => extracting sha256:004f1eed87df3f75f5e2a1a649fa7edd7f713d1300532fd0909bb39cd48437d7                                                              8.6s
 => => extracting sha256:5d6f1e8117dbb1c6a57603cb4f321a861a08105a81bcc6b01b0ec2b78c8523a5                                                              0.7s
 => => extracting sha256:48c2faf66abec3dce9f54d6722ff592fce6dd4fb58a0d0b72282936c6598a3b3                                                              0.6s
 => => extracting sha256:234b70d0479d7f16d7ee8d04e4ffdacc57d7d14313faf59d332f18b2e9418743                                                              6.0s
 => => extracting sha256:6fa07a00e2f029c4b2c7f177a2b696f1b3510040cde4f5bb06ddbca98e7fbf76                                                             14.9s
 => => extracting sha256:04a31b4508b8e95fb3cb25486c4068185054895b12e0611e386a002ee9c0e07c                                                              0.5s
 => => extracting sha256:d71f59bc3dca0b4ed1abbeb5f8881d9038117b4afc5db3645ccde089855a0ff7                                                              2.2s
 => => extracting sha256:1417d35049f1a001c25031a8a86d6352a730aa7a4026a1bbac4c948c03c88a78                                                              0.0s
 => => extracting sha256:7deb1706395d9c9f7aceb648e2576c63f8faa97b520eb37f69559221aa8e9ac5                                                              0.4s
 => [internal] load build context                                                                                                                      0.0s
 => => transferring context: 5.54kB                                                                                                                    0.0s
 => [2/6] COPY requirements.txt /tmp/                                                                                                                  0.4s
 => [3/6] COPY ./install/docker/wait-for-it.sh /usr/local/bin/                                                                                         0.0s
 => [4/6] RUN chmod +x /usr/local/bin/wait-for-it.sh                                                                                                   0.7s
 => [5/6] RUN pip install --upgrade pip && pip install -r /tmp/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple                           49.3s
 => [6/6] RUN pip install MarkupSafe==1.1.1 -i https://pypi.tuna.tsinghua.edu.cn/simple                                                                2.8s
 => exporting to image                                                                                                                                 0.9s
 => => exporting layers                                                                                                                                0.9s
 => => writing image sha256:5e1b1cc3816d079b64b51b3f50b69496453f1c58e9bd97651200fe52f8f5bdc5                                                           0.0s
 => => naming to docker.io/library/ocean_web:v1                                                                                                        0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 4/5
 - Network ocean_ctf-main_default  Created                                                                                                             0.1s
 - Container nginx                 Starting                                                                                                            1.7s
 - Container db                    Started                                                                                                             1.3s
 - Container redis                 Started                                                                                                             1.2s
 - Container web                   Started                                                                                                             1.6s
Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:75: mounting "/opt/ocean_ctf/install/nginx.conf" to rootfs at "/etc/nginx/nginx.conf" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
PS C:\Users\HSM\Desktop\ocean_ctf-main\ocean_ctf-main> docker-compose up -d
[+] Running 3/4
 - Container redis  Started                                                                                                                            2.4s
 - Container nginx  Starting                                                                                                                           3.0s
 - Container db     Started                                                                                                                            2.5s
 - Container web    Started                                                                                                                            1.6s
Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:75: mounting "/opt/ocean_ctf/install/nginx.conf" to rootfs at "/etc/nginx/nginx.conf" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by tongchengbin** [comment]
代码路径错误 按照文档clone 到/opt/ 目录下
