### ISSUE TITLE
使用容器管理中的添加镜像报错

### ISSUE THREAD

**Issue by xiaoshengbaiyi** [tongchengbin/ocean_ctf#31]
后台系统：Ubuntu20.4
docker 版本：20.10.14,
docker-compose 版本：1.25.0,
使用的后台都是由于docker-compose直接构建的

我修改了报错内容
![image](https://user-images.githubusercontent.com/44537257/167282435-b51b6da0-c669-4ca8-95fb-ab983acd7529.png)

就得到了如下报错
![image](https://user-images.githubusercontent.com/44537257/167282269-a0cc64b9-de3c-4dfa-a16a-b27e0230ca84.png)

**Comment by tongchengbin** [comment]
建议使用资源中心添加题目

**Comment by tongchengbin** [comment]
> 后台系统：Ubuntu20.4 docker 版本：20.10.14, docker-compose 版本：1.25.0, 使用的后台都是由于docker-compose直接构建的
> 
> 我修改了报错内容 ![image](https://user-images.githubusercontent.com/44537257/167282435-b51b6da0-c669-4ca8-95fb-ab983acd7529.png)
> 
> 就得到了如下报错 ![image](https://user-images.githubusercontent.com/44537257/167282269-a0cc64b9-de3c-4dfa-a16a-b27e0230ca84.png)

可以试试新版本中的资源中心添加题目资源
