### ISSUE TITLE
动态靶机部署问题

### ISSUE THREAD

**Issue by seizer-zyx** [tongchengbin/ocean_ctf#33]
- 通过看源码发现是通过执行/start.sh来实现动态flag，因为本身环境里没有start.sh所以导致开题目的时候会报500
通过解决后，还发现以下问题无法解决：
1. 后台赛事配置里无法修改容器时长
2. 开启题目后显示异常，但可正常打开题目，提交flag也会报500
![image](https://user-images.githubusercontent.com/73650154/180176233-a5afac43-aeaa-4045-acb1-bed582eeb305.png)
**请问有师傅们解决这些问题了吗？**

**Comment by tongchengbin** [comment]
使用新版本的试一下

> * 通过看源码发现是通过执行/start.sh来实现动态flag，因为本身环境里没有start.sh所以导致开题目的时候会报500
>   通过解决后，还发现以下问题无法解决：
> 
> 1. 后台赛事配置里无法修改容器时长
> 2. 开启题目后显示异常，但可正常打开题目，提交flag也会报500
>    ![image](https://user-images.githubusercontent.com/73650154/180176233-a5afac43-aeaa-4045-acb1-bed582eeb305.png)
>    **请问有师傅们解决这些问题了吗？**

使用新版本的测试一下
