### ISSUE TITLE
容器管理直接没了？？？

### ISSUE THREAD

**Issue by Le1a** [tongchengbin/ocean_ctf#34]
![image](https://user-images.githubusercontent.com/97610822/180603612-3576747e-6b04-4a60-95e9-2614ff276d79.png)

**Comment by tongchengbin** [comment]
感觉前面的操作太麻烦了 直接在虚拟化管理中上传镜像即可，或者自己打包镜像 题目编辑中就可以选择对应镜像了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月23日(周六) 晚上7:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [tongchengbin/ocean_ctf] 容器管理直接没了？？？ (Issue #34)
