### ISSUE TITLE
Error response from daemon: Cannot restart container 8588ce4581fa: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "celery": executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by yzhangmin** [tongchengbin/ocean_ctf#39]
Error response from daemon: Cannot restart container 8588ce4581fa: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "celery": executable file not found in $PATH: unknown

**Comment by tongchengbin** [comment]
删除ocean_web 镜像文件后重新编排看一下

**Comment by a83376114** [comment]
> 

要咋操作呢，我也遇到了同样的问题

**Comment by a83376114** [comment]
> 删除ocean_web 镜像文件后重新编排看一下

要咋操作呢，我也遇到了同样的问题

**Comment by tongchengbin** [comment]
> 

QQ 58296672 远程看一下

**Comment by tongchengbin** [comment]
> > 删除ocean_web 镜像文件后重新编排看一下
> 
> 要咋操作呢，我也遇到了同样的问题

QQ 58296672 远程看一下

**Comment by a83376114** [comment]
> > > 删除ocean_web 镜像文件后重新编排看一下
> > 
> > 
> > 要咋操作呢，我也遇到了同样的问题
> 
> QQ 58296672 远程看一下

明白这个操作了，也应该找到了问题的所在。在Mac下会出现楼主的问题，但在WSL下可以正常跑通。
