### ISSUE TITLE
题目会重复添加

### ISSUE THREAD

**Issue by yzhangmin** [tongchengbin/ocean_ctf#40]
![image](https://user-images.githubusercontent.com/22231326/217709991-96914d78-2ac3-4f38-b1f0-234c92212643.png)

**Comment by yzhangmin** [comment]
![image](https://user-images.githubusercontent.com/22231326/217710420-3904b701-b57e-4027-b3e1-06f7af4ab133.png)

**Comment by yzhangmin** [comment]
![image](https://user-images.githubusercontent.com/22231326/217731992-8eb7a14c-950b-4278-b934-7cd75ead6fe5.png)
删除的时候提示的错误

**Comment by tongchengbin** [comment]
v3 已解决
