### ISSUE TITLE
虚拟化-资源中心，添加资源，加载类型中只显示远程镜像，没有本地镜像

### ISSUE THREAD

**Issue by wanswu** [tongchengbin/ocean_ctf#41]
![image](https://user-images.githubusercontent.com/49047734/225264949-18270fda-cbe6-436a-a10c-c5d942b9bbe4.png)

**Comment by Ashe233** [comment]
同问

**Comment by tongchengbin** [comment]
选择远程镜像之后直接输入本地镜像名称即可
