### ISSUE TITLE
添加题目有的时候点击确定没反应

### ISSUE THREAD

**Issue by czheisenberg** [tongchengbin/ocean_ctf#47]
添加题目有的时候点击确定没反应

**Comment by tongchengbin** [comment]
请提供一下操作流程或浏览器控制台日志



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月4日(周一) 上午9:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [tongchengbin/ocean_ctf] 添加题目有的时候点击确定没反应 (Issue #47)




 
添加题目有的时候点击确定没反应

**Comment by czheisenberg** [comment]
![image](https://github.com/tongchengbin/ocean_ctf/assets/52897817/c6efa4a7-d71c-4eee-9f47-9fa0aa88f722)

日志:
POST http://labs.ctf.asia/api/admin/ctf/question 400 (BAD REQUEST)			index-dDoYVgIf.js:72 
(匿名) @ index-dDoYVgIf.js:72
xhr @ index-dDoYVgIf.js:72
_w @ index-dDoYVgIf.js:74
Promise.then(异步)
_request @ index-dDoYVgIf.js:75
request @ index-dDoYVgIf.js:74
(匿名) @ index-dDoYVgIf.js:70
(匿名) @ index-dDoYVgIf.js:83
request @ index-dDoYVgIf.js:83
post @ index-dDoYVgIf.js:83
(匿名) @ questionItem-DSGwMaEs.js:1
g @ index-dDoYVgIf.js:21
await in g(异步)
v @ index-dDoYVgIf.js:21
submit @ questionItem-DSGwMaEs.js:1
Sr @ index-dDoYVgIf.js:13
no @ index-dDoYVgIf.js:13
aT @ index-dDoYVgIf.js:13
handleClick @ index-dDoYVgIf.js:40
Sr @ index-dDoYVgIf.js:13
no @ index-dDoYVgIf.js:13
n @ index-dDoYVgIf.js:17

(匿名)	@	index-dDoYVgIf.js:72
xhr	@	index-dDoYVgIf.js:72
_w	@	index-dDoYVgIf.js:74
Promise.then(异步)		
_request	@	index-dDoYVgIf.js:75
request	@	index-dDoYVgIf.js:74
(匿名)	@	index-dDoYVgIf.js:70
(匿名)	@	index-dDoYVgIf.js:83
request	@	index-dDoYVgIf.js:83
post	@	index-dDoYVgIf.js:83
(匿名)	@	questionItem-DSGwMaEs.js:1
g	@	index-dDoYVgIf.js:21
await in g(异步)		
v	@	index-dDoYVgIf.js:21
submit	@	questionItem-DSGwMaEs.js:1
Sr	@	index-dDoYVgIf.js:13
no	@	index-dDoYVgIf.js:13
aT	@	index-dDoYVgIf.js:13
handleClick	@	index-dDoYVgIf.js:40
Sr	@	index-dDoYVgIf.js:13
no	@	index-dDoYVgIf.js:13
n	@	index-dDoYVgIf.js:17

![image](https://github.com/tongchengbin/ocean_ctf/assets/52897817/aa50a0f7-b1b4-421d-9863-7218ea510a5f)

**Comment by czheisenberg** [comment]
我解决了
