### ISSUE TITLE
添加镜像时提示镜像名称和版本不支持特殊字符

### ISSUE THREAD

**Issue by godamos** [tongchengbin/ocean_ctf#50]
你好，我在使用ocean_ctf在添加镜像时提示镜像名称和版本不支持特殊字符，无论是dockerfile还是上传还是pull都是提示这个，请问该怎么解决？
我用的镜像名为ctftraining/swpuctf_2016_web_web7:latest、swpuctf_2016_web_web7:latest、swpuctf_2016_web_web7、ctftraining/swpuctf_2016_web_web7都是提示这个

**Comment by tongchengbin** [comment]
docker 镜像和容器禁止特殊字符和中文 因此不支持，但是可以在资源中使用中文名或特殊字符 关联对应的镜像就行了

**Comment by tongchengbin** [comment]
请提供截图日志



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月28日(周四) 上午10:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tongchengbin/ocean_ctf] 添加镜像时提示镜像名称和版本不支持特殊字符 (Issue #50)




 
我并没有使用中文和特殊字符，:是tag必须的字符，使用不带_的也是爆这个错误

**Comment by godamos** [comment]
<img width="942" alt="image" src="https://github.com/tongchengbin/ocean_ctf/assets/23711955/6943e28c-5cb3-4057-85e3-11db69397cfb">

**Comment by tongchengbin** [comment]
镜像名中没有考虑/导致的，下版本会处理，可以手动拉取下来重命名一下临时解决



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月30日(周六) 晚上8:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tongchengbin/ocean_ctf] 添加镜像时提示镜像名称和版本不支持特殊字符 (Issue #50)




 image.png (view on web)
