### ISSUE TITLE
无法访问

### ISSUE THREAD

**Issue by boybarefoot** [tongchengbin/ocean_ctf#7]
![image](https://user-images.githubusercontent.com/56615760/132867582-f65430a3-8e97-4ead-9b47-933ede0f5744.png)
![image](https://user-images.githubusercontent.com/56615760/132867661-04b4703d-dc7d-4c16-9c28-f09a64f052b5.png)

**Comment by boybarefoot** [comment]
开发者您好，这种问题如何解决呢？

**Comment by boybarefoot** [comment]
服务起不起来

**Comment by tongchengbin** [comment]
docker logs -f web  看一下web未启动的原因 目前存在的问题是由于web启动时 mysql未初始化完成导致启动失败  可以尝试单独重启web 试一下 如果还是无法启动请发web 日志给我
