### ISSUE TITLE
删除题目接口问题

### ISSUE THREAD

**Issue by zhang192073** [tongchengbin/ocean_ctf#9]
![image](https://user-images.githubusercontent.com/47629854/138088457-405dc7b7-de03-45eb-8ac6-c92705455afa.png)

![image](https://user-images.githubusercontent.com/47629854/138088544-4e394493-0e34-4e2e-be23-8969e0d70036.png)

![image](https://user-images.githubusercontent.com/47629854/138088600-742c31b9-9a7b-4dcd-aec8-3b95a5570a1f.png)

**Comment by tongchengbin** [comment]
fix
